select*from customer limit 20

--q1.which is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as revenue
from customer
group by gender

--q2.Which customer used a discount but still spend more than the average purchase amount?
select customer_id,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from customer)

--q3.Which are the top 5 product with the highest average review rating?
select item_purchased,Round(avg(review_rating::numeric),2) as average_rating from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--q4.Compare the average purchase amount between standard and Express shipping
select shipping_type,round(avg(purchase_amount),2) as average_purchase
from customer
where shipping_type in ('Express','Standard')
group by shipping_type
order by shipping_type,average_purchase desc

--q5.Do subscribed customer spend more? 
--Compare average spend and total revenue between subscribers an non-subscribers
select subscription_status,count(customer_id),Round(avg(purchase_amount),2) as average_spend,
sum(purchase_amount) as total_revenue 
from customer
group by subscription_status
order by average_spend,total_revenue  desc 

--q6.Which 5 product have the highest percentage of purchases of purchases with discounts applied?
select item_purchased,
round(100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate 
from customer
group by item_purchased
order by discount_rate desc

--q7.segment customer int new,returning,and loyal based on their total 
--number of previous purchase,and show the count of each segment.
with customer_type as(
select customer_id,previous_purchases,
case 
      when previous_purchases=1 then 'New'
	  when previous_purchases between 2 and 10 then 'Returning'
	  else 'loyal'
	  end as customer_segment
from customer
)
select customer_segment,count(*) as "Number of customers"
from customer_type
group by customer_segment

--q8.What are the top 3 most purchased products within each category?
with item_category as(
select category,item_purchased,count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id)desc) as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_category
where item_rank<=3 

--q9.Are customer who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5 
group by subscription_status

--q10.What is the revenue contribution of each age group?
select age_group,sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc
